### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by maierfelix** [brendan-duncan/webgpu_inspector#21]
For some URLs like `http://localhost:5800` I'm getting `Failed to construct 'URL': Invalid URL` in https://github.com/brendan-duncan/webgpu_inspector/blob/dbb8ebc8d034b6d0cd573e0c4573e9c88cd457e5/src/webgpu_inspector.js#L2019

**Comment by brendan-duncan** [comment]
Can you provide a small repo? I tried a few URL patterns like you suggested, but haven't hit the error yet.

**Comment by brendan-duncan** [comment]
I found a repo for the error. Not sure if it's the same issue you have or not. I pushed an update to github that seems to get around the problem I saw in testing, which is the pattern `new Worker("/foo/bar.js")`.

**Comment by maierfelix** [comment]
Thanks for looking into this! Yes I just checked the url and it's indeed a path without hostname which `new URL()` then throws an error for.

**Comment by maierfelix** [comment]
It still throws an error during the URL construction [here](https://github.com/brendan-duncan/webgpu_inspector/blob/bdc0da5fcd8d206a8c79608948912db7cb3244c6/src/webgpu_inspector.js#L2025). In my case the URL is: `http://localhost:5800./js/test.js`. Changing the URL construction to ``
_url = new URL(`${baseUrl.protocol}//${baseUrl.host}/${url}`);
`` fixed it for me

**Comment by brendan-duncan** [comment]
Thanks for the extra info, I'll look into it soon. I suppose the additional fix is to check if url starts with a "/" or not, and add the "/" if not.

**Comment by brendan-duncan** [comment]
I pushed a fix for that to git.

**Comment by maierfelix** [comment]
It works, thanks a lot!

**Comment by fanciful-marmot** [comment]
@brendan-duncan Is it possible to get this fix released to the chrome extension?

**Comment by brendan-duncan** [comment]
Oh yeah, sure. I got distracted by work and forgot. I'll push a chrome store update today, and it'll take a day or so for it to go public.

**Comment by brendan-duncan** [comment]
I submitted the update to the chrome store.

**Comment by brendan-duncan** [comment]
It's on the store now. I'll go ahead and close the ticket.
